import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';
import { jsPDF } from 'npm:jspdf@2.5.1';

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();

        if (!user || user.role !== 'admin') {
            return Response.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { recipients, subject, message, format, donations, filters } = await req.json();

        if (!recipients || recipients.length === 0) {
            return Response.json({ error: 'No recipients specified' }, { status: 400 });
        }

        let reportData;
        let mimeType;
        let fileName;

        if (format === 'pdf') {
            // Generate PDF
            const pdfResponse = await base44.functions.invoke('exportFinancialReportPDF', {
                donations,
                filters
            });
            reportData = pdfResponse.data.pdf_data;
            mimeType = 'application/pdf';
            fileName = `financial-report-${new Date().toISOString().split('T')[0]}.pdf`;
        } else {
            // Generate CSV
            const csvResponse = await base44.functions.invoke('exportFinancialReportCSV', {
                donations,
                filters
            });
            reportData = csvResponse.data.csv_data;
            mimeType = 'text/csv';
            fileName = `financial-report-${new Date().toISOString().split('T')[0]}.csv`;
        }

        // Upload report to storage
        const blob = format === 'pdf' 
            ? new Blob([new Uint8Array(reportData)], { type: mimeType })
            : new Blob([reportData], { type: mimeType });

        const file = new File([blob], fileName, { type: mimeType });
        
        const uploadResponse = await base44.asServiceRole.integrations.Core.UploadFile({ file });
        const fileUrl = uploadResponse.file_url;

        // Get church settings
        const settings = await base44.asServiceRole.entities.ChurchSettings.list();
        const churchName = settings.length > 0 ? settings[0].church_name : 'Church';

        // Send to each recipient
        let successCount = 0;
        for (const recipient of recipients) {
            try {
                const emailBody = `${message}

Report Details:
- Period: ${filters.dateFrom} to ${filters.dateTo}
- Total Donations: $${donations.reduce((sum, d) => sum + d.amount, 0).toLocaleString()}
- Total Transactions: ${donations.length}

Download your report: ${fileUrl}

This report was generated by ${user.full_name || user.email}.

Best regards,
${churchName}`;

                await base44.asServiceRole.integrations.Core.SendEmail({
                    from_name: churchName,
                    to: recipient,
                    subject: subject,
                    body: emailBody
                });

                successCount++;
                await new Promise(resolve => setTimeout(resolve, 300));
            } catch (error) {
                console.error(`Failed to send to ${recipient}:`, error);
            }
        }

        return Response.json({
            success: true,
            sent: successCount,
            total: recipients.length
        });

    } catch (error) {
        console.error('Distribution error:', error);
        return Response.json({ 
            error: error.message 
        }, { status: 500 });
    }
});